services:
  - type: web
    name: acme-salary-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: AUTH_ENABLED
        value: true
      - key: AUTH_USER
        value: admin
      - key: AUTH_PASS
        sync: false
      - key: AUTH_SECRET
        sync: false

staticSites:
  - name: acme-salary-ui
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
